# Generated by Django 4.0.3 on 2022-07-18 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(blank=True, related_name='blockedProfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
